// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/pocketcore/pocket.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_pokt_network_pocket_core_types "github.com/pokt-network/pocket-core/types"
	types "github.com/pokt-network/pocket-core/x/nodes/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SessionHeader defines the header for session information
type SessionHeader struct {
	ApplicationPubKey  string `protobuf:"bytes,1,opt,name=applicationPubKey,proto3" json:"app_public_key"`
	Chain              string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain"`
	SessionBlockHeight int64  `protobuf:"varint,3,opt,name=sessionBlockHeight,proto3" json:"session_height"`
}

func (m *SessionHeader) Reset()         { *m = SessionHeader{} }
func (m *SessionHeader) String() string { return proto.CompactTextString(m) }
func (*SessionHeader) ProtoMessage()    {}
func (*SessionHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{0}
}
func (m *SessionHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SessionHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SessionHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SessionHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionHeader.Merge(m, src)
}
func (m *SessionHeader) XXX_Size() int {
	return m.Size()
}
func (m *SessionHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SessionHeader proto.InternalMessageInfo

type ProtoSession struct {
	SessionHeader SessionHeader     `protobuf:"bytes,1,opt,name=sessionHeader,proto3" json:"header"`
	SessionKey    SessionKey        `protobuf:"bytes,2,opt,name=sessionKey,proto3,casttype=SessionKey" json:"key"`
	SessionNodes  ProtoSessionNodes `protobuf:"bytes,3,rep,name=sessionNodes,proto3,castrepeated=ProtoSessionNodes" json:"nodes"`
}

func (m *ProtoSession) Reset()         { *m = ProtoSession{} }
func (m *ProtoSession) String() string { return proto.CompactTextString(m) }
func (*ProtoSession) ProtoMessage()    {}
func (*ProtoSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{1}
}
func (m *ProtoSession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProtoSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProtoSession.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProtoSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoSession.Merge(m, src)
}
func (m *ProtoSession) XXX_Size() int {
	return m.Size()
}
func (m *ProtoSession) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoSession.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoSession proto.InternalMessageInfo

type MsgClaim struct {
	SessionHeader    SessionHeader                                     `protobuf:"bytes,1,opt,name=sessionHeader,proto3" json:"header"`
	MerkleRoot       HashRange                                         `protobuf:"bytes,2,opt,name=merkleRoot,proto3" json:"merkle_root"`
	TotalProofs      int64                                             `protobuf:"varint,3,opt,name=totalProofs,proto3" json:"total_proofs"`
	FromAddress      github_com_pokt_network_pocket_core_types.Address `protobuf:"bytes,4,opt,name=fromAddress,proto3,casttype=github.com/pokt-network/pocket-core/types.Address" json:"from_address"`
	EvidenceType     EvidenceType                                      `protobuf:"varint,5,opt,name=evidenceType,proto3,casttype=EvidenceType" json:"evidence_type"`
	ExpirationHeight int64                                             `protobuf:"varint,6,opt,name=expirationHeight,proto3" json:"expiration_height"`
}

func (m *MsgClaim) Reset()         { *m = MsgClaim{} }
func (m *MsgClaim) String() string { return proto.CompactTextString(m) }
func (*MsgClaim) ProtoMessage()    {}
func (*MsgClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{2}
}
func (m *MsgClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaim.Merge(m, src)
}
func (m *MsgClaim) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaim.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaim proto.InternalMessageInfo

func (*MsgClaim) XXX_MessageName() string {
	return "x.pocketcore.MsgClaim"
}

type MsgProtoProof struct {
	MerkleProof  MerkleProof  `protobuf:"bytes,1,opt,name=merkleProof,proto3" json:"merkle_proofs"`
	Leaf         ProofI       `protobuf:"bytes,2,opt,name=leaf,proto3" json:"leaf"`
	EvidenceType EvidenceType `protobuf:"varint,3,opt,name=evidenceType,proto3,casttype=EvidenceType" json:"evidence_type"`
}

func (m *MsgProtoProof) Reset()         { *m = MsgProtoProof{} }
func (m *MsgProtoProof) String() string { return proto.CompactTextString(m) }
func (*MsgProtoProof) ProtoMessage()    {}
func (*MsgProtoProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{3}
}
func (m *MsgProtoProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProtoProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProtoProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProtoProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProtoProof.Merge(m, src)
}
func (m *MsgProtoProof) XXX_Size() int {
	return m.Size()
}
func (m *MsgProtoProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProtoProof.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProtoProof proto.InternalMessageInfo

func (*MsgProtoProof) XXX_MessageName() string {
	return "x.pocketcore.MsgProtoProof"
}

type ProofI struct {
	// Types that are valid to be assigned to Proof:
	//	*ProofI_RelayProof
	//	*ProofI_ChallengeProof
	Proof isProofI_Proof `protobuf_oneof:"proof"`
}

func (m *ProofI) Reset()         { *m = ProofI{} }
func (m *ProofI) String() string { return proto.CompactTextString(m) }
func (*ProofI) ProtoMessage()    {}
func (*ProofI) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{4}
}
func (m *ProofI) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProofI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProofI.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProofI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofI.Merge(m, src)
}
func (m *ProofI) XXX_Size() int {
	return m.Size()
}
func (m *ProofI) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofI.DiscardUnknown(m)
}

var xxx_messageInfo_ProofI proto.InternalMessageInfo

type isProofI_Proof interface {
	isProofI_Proof()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ProofI_RelayProof struct {
	RelayProof *RelayProof `protobuf:"bytes,1,opt,name=relayProof,proto3,oneof" json:"relayProof,omitempty"`
}
type ProofI_ChallengeProof struct {
	ChallengeProof *ChallengeProofInvalidData `protobuf:"bytes,2,opt,name=challengeProof,proto3,oneof" json:"challengeProof,omitempty"`
}

func (*ProofI_RelayProof) isProofI_Proof()     {}
func (*ProofI_ChallengeProof) isProofI_Proof() {}

func (m *ProofI) GetProof() isProofI_Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *ProofI) GetRelayProof() *RelayProof {
	if x, ok := m.GetProof().(*ProofI_RelayProof); ok {
		return x.RelayProof
	}
	return nil
}

func (m *ProofI) GetChallengeProof() *ChallengeProofInvalidData {
	if x, ok := m.GetProof().(*ProofI_ChallengeProof); ok {
		return x.ChallengeProof
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProofI) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProofI_RelayProof)(nil),
		(*ProofI_ChallengeProof)(nil),
	}
}

type ProtoEvidence struct {
	BloomBytes    []byte         `protobuf:"bytes,1,opt,name=bloomBytes,proto3" json:"bloom_bytes"`
	SessionHeader *SessionHeader `protobuf:"bytes,2,opt,name=sessionHeader,proto3" json:"evidence_header"`
	NumOfProofs   int64          `protobuf:"varint,3,opt,name=numOfProofs,proto3" json:"num_of_proofs"`
	Proofs        ProofIs        `protobuf:"bytes,4,rep,name=proofs,proto3,castrepeated=ProofIs" json:"proofs"`
	EvidenceType  EvidenceType   `protobuf:"varint,5,opt,name=evidenceType,proto3,casttype=EvidenceType" json:"evidence_type"`
}

func (m *ProtoEvidence) Reset()         { *m = ProtoEvidence{} }
func (m *ProtoEvidence) String() string { return proto.CompactTextString(m) }
func (*ProtoEvidence) ProtoMessage()    {}
func (*ProtoEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{5}
}
func (m *ProtoEvidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProtoEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProtoEvidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProtoEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoEvidence.Merge(m, src)
}
func (m *ProtoEvidence) XXX_Size() int {
	return m.Size()
}
func (m *ProtoEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoEvidence proto.InternalMessageInfo

type RelayProof struct {
	RequestHash        string `protobuf:"bytes,1,opt,name=requestHash,proto3" json:"request_hash"`
	Entropy            int64  `protobuf:"varint,2,opt,name=entropy,proto3" json:"entropy"`
	SessionBlockHeight int64  `protobuf:"varint,3,opt,name=sessionBlockHeight,proto3" json:"session_block_height"`
	ServicerPubKey     string `protobuf:"bytes,4,opt,name=servicerPubKey,proto3" json:"servicer_pub_key"`
	Blockchain         string `protobuf:"bytes,5,opt,name=blockchain,proto3" json:"blockchain"`
	Token              AAT    `protobuf:"bytes,6,opt,name=token,proto3" json:"aat"`
	Signature          string `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature"`
}

func (m *RelayProof) Reset()         { *m = RelayProof{} }
func (m *RelayProof) String() string { return proto.CompactTextString(m) }
func (*RelayProof) ProtoMessage()    {}
func (*RelayProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{6}
}
func (m *RelayProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayProof.Merge(m, src)
}
func (m *RelayProof) XXX_Size() int {
	return m.Size()
}
func (m *RelayProof) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayProof.DiscardUnknown(m)
}

var xxx_messageInfo_RelayProof proto.InternalMessageInfo

type ChallengeProofInvalidData struct {
	MajorityResponses []RelayResponse                                   `protobuf:"bytes,1,rep,name=majorityResponses,proto3" json:"majority_responses"`
	MinorityResponse  RelayResponse                                     `protobuf:"bytes,2,opt,name=minorityResponse,proto3" json:"minority_response"`
	ReporterAddress   github_com_pokt_network_pocket_core_types.Address `protobuf:"bytes,3,opt,name=reporterAddress,proto3,casttype=github.com/pokt-network/pocket-core/types.Address" json:"reporters_address"`
}

func (m *ChallengeProofInvalidData) Reset()         { *m = ChallengeProofInvalidData{} }
func (m *ChallengeProofInvalidData) String() string { return proto.CompactTextString(m) }
func (*ChallengeProofInvalidData) ProtoMessage()    {}
func (*ChallengeProofInvalidData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{7}
}
func (m *ChallengeProofInvalidData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChallengeProofInvalidData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChallengeProofInvalidData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChallengeProofInvalidData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChallengeProofInvalidData.Merge(m, src)
}
func (m *ChallengeProofInvalidData) XXX_Size() int {
	return m.Size()
}
func (m *ChallengeProofInvalidData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChallengeProofInvalidData.DiscardUnknown(m)
}

var xxx_messageInfo_ChallengeProofInvalidData proto.InternalMessageInfo

type RelayResponse struct {
	Signature string     `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature"`
	Response  string     `protobuf:"bytes,2,opt,name=response,proto3" json:"payload"`
	Proof     RelayProof `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof"`
}

func (m *RelayResponse) Reset()         { *m = RelayResponse{} }
func (m *RelayResponse) String() string { return proto.CompactTextString(m) }
func (*RelayResponse) ProtoMessage()    {}
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{8}
}
func (m *RelayResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayResponse.Merge(m, src)
}
func (m *RelayResponse) XXX_Size() int {
	return m.Size()
}
func (m *RelayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RelayResponse proto.InternalMessageInfo

type AAT struct {
	Version              string `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`
	ApplicationPublicKey string `protobuf:"bytes,2,opt,name=applicationPublicKey,proto3" json:"app_pub_key"`
	ClientPublicKey      string `protobuf:"bytes,3,opt,name=clientPublicKey,proto3" json:"client_pub_key"`
	ApplicationSignature string `protobuf:"bytes,4,opt,name=applicationSignature,proto3" json:"signature"`
}

func (m *AAT) Reset()         { *m = AAT{} }
func (m *AAT) String() string { return proto.CompactTextString(m) }
func (*AAT) ProtoMessage()    {}
func (*AAT) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{9}
}
func (m *AAT) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AAT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AAT.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AAT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AAT.Merge(m, src)
}
func (m *AAT) XXX_Size() int {
	return m.Size()
}
func (m *AAT) XXX_DiscardUnknown() {
	xxx_messageInfo_AAT.DiscardUnknown(m)
}

var xxx_messageInfo_AAT proto.InternalMessageInfo

type MerkleProof struct {
	TargetIndex int64       `protobuf:"varint,1,opt,name=TargetIndex,proto3" json:"index"`
	HashRanges  []HashRange `protobuf:"bytes,2,rep,name=hashRanges,proto3" json:"hash_ranges"`
	Target      HashRange   `protobuf:"bytes,3,opt,name=target,proto3" json:"target_range"`
}

func (m *MerkleProof) Reset()         { *m = MerkleProof{} }
func (m *MerkleProof) String() string { return proto.CompactTextString(m) }
func (*MerkleProof) ProtoMessage()    {}
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{10}
}
func (m *MerkleProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MerkleProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MerkleProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MerkleProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleProof.Merge(m, src)
}
func (m *MerkleProof) XXX_Size() int {
	return m.Size()
}
func (m *MerkleProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleProof.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleProof proto.InternalMessageInfo

// Range for merkle sum index tree
type Range struct {
	Lower uint64 `protobuf:"varint,1,opt,name=lower,proto3" json:"lower"`
	Upper uint64 `protobuf:"varint,2,opt,name=upper,proto3" json:"upper"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{11}
}
func (m *Range) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Range.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return m.Size()
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

type HashRange struct {
	Hash  []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"merkleHash"`
	Range Range  `protobuf:"bytes,2,opt,name=range,proto3" json:"range"`
}

func (m *HashRange) Reset()         { *m = HashRange{} }
func (m *HashRange) String() string { return proto.CompactTextString(m) }
func (*HashRange) ProtoMessage()    {}
func (*HashRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd7cbfa14fd73888, []int{12}
}
func (m *HashRange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashRange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRange.Merge(m, src)
}
func (m *HashRange) XXX_Size() int {
	return m.Size()
}
func (m *HashRange) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRange.DiscardUnknown(m)
}

var xxx_messageInfo_HashRange proto.InternalMessageInfo

func (m *HashRange) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *HashRange) GetRange() Range {
	if m != nil {
		return m.Range
	}
	return Range{}
}

func init() {
	proto.RegisterType((*SessionHeader)(nil), "x.pocketcore.SessionHeader")
	proto.RegisterType((*ProtoSession)(nil), "x.pocketcore.ProtoSession")
	proto.RegisterType((*MsgClaim)(nil), "x.pocketcore.MsgClaim")
	proto.RegisterType((*MsgProtoProof)(nil), "x.pocketcore.MsgProtoProof")
	proto.RegisterType((*ProofI)(nil), "x.pocketcore.ProofI")
	proto.RegisterType((*ProtoEvidence)(nil), "x.pocketcore.ProtoEvidence")
	proto.RegisterType((*RelayProof)(nil), "x.pocketcore.RelayProof")
	proto.RegisterType((*ChallengeProofInvalidData)(nil), "x.pocketcore.ChallengeProofInvalidData")
	proto.RegisterType((*RelayResponse)(nil), "x.pocketcore.RelayResponse")
	proto.RegisterType((*AAT)(nil), "x.pocketcore.AAT")
	proto.RegisterType((*MerkleProof)(nil), "x.pocketcore.MerkleProof")
	proto.RegisterType((*Range)(nil), "x.pocketcore.Range")
	proto.RegisterType((*HashRange)(nil), "x.pocketcore.HashRange")
}

func init() { proto.RegisterFile("x/pocketcore/pocket.proto", fileDescriptor_fd7cbfa14fd73888) }

var fileDescriptor_fd7cbfa14fd73888 = []byte{
	// 1350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x4d, 0xc9, 0x8e, 0x47, 0x92, 0x6d, 0xad, 0x1d, 0x54, 0x4e, 0x01, 0xd3, 0x35, 0x50,
	0xc4, 0x40, 0x10, 0x19, 0x75, 0xda, 0xa0, 0x08, 0x52, 0xa0, 0x62, 0x6a, 0xd4, 0x69, 0x9b, 0xc6,
	0xd9, 0x18, 0x39, 0xf4, 0x22, 0x50, 0xd4, 0x5a, 0x62, 0x45, 0x71, 0x59, 0x72, 0xe5, 0x58, 0x6f,
	0x90, 0x63, 0x1f, 0xa1, 0xe8, 0xa1, 0x87, 0x3c, 0x43, 0x1f, 0x20, 0xc7, 0x5c, 0x0a, 0xf4, 0x50,
	0x30, 0x85, 0x7d, 0x13, 0xfa, 0x00, 0x45, 0x2e, 0x2d, 0x76, 0x76, 0x29, 0x91, 0xb6, 0xe2, 0x16,
	0xfd, 0xb9, 0x88, 0xe4, 0xcc, 0x37, 0xb3, 0xf3, 0xb3, 0xf3, 0x23, 0x58, 0x3f, 0xd9, 0x09, 0xb9,
	0xdb, 0x67, 0xc2, 0xe5, 0x11, 0xd3, 0xaf, 0x8d, 0x30, 0xe2, 0x82, 0x93, 0xca, 0x49, 0x63, 0xca,
	0xba, 0xb6, 0xd6, 0xe5, 0x5d, 0x8e, 0x8c, 0x1d, 0xf9, 0xa6, 0x30, 0xd7, 0x56, 0x4f, 0x76, 0x02,
	0xde, 0x61, 0xb1, 0xfa, 0x55, 0xc4, 0xad, 0x1f, 0x0d, 0xa8, 0x3e, 0x66, 0x71, 0xec, 0xf1, 0x60,
	0x9f, 0x39, 0x1d, 0x16, 0x91, 0x8f, 0xa1, 0xe6, 0x84, 0xa1, 0xef, 0xb9, 0x8e, 0xf0, 0x78, 0x70,
	0x30, 0x6c, 0x7f, 0xce, 0x46, 0x75, 0x63, 0xd3, 0xd8, 0x5e, 0xb4, 0xc9, 0x38, 0xb1, 0x96, 0x9c,
	0x30, 0x6c, 0x85, 0xc3, 0xb6, 0xef, 0xb9, 0xad, 0x3e, 0x1b, 0xd1, 0x8b, 0x60, 0x62, 0x41, 0xc9,
	0xed, 0x39, 0x5e, 0x50, 0x9f, 0x43, 0xa9, 0xc5, 0x71, 0x62, 0x29, 0x02, 0x55, 0x0f, 0x62, 0x03,
	0x89, 0xd5, 0x99, 0xb6, 0xcf, 0xdd, 0xfe, 0x3e, 0xf3, 0xba, 0x3d, 0x51, 0x37, 0x37, 0x8d, 0x6d,
	0x53, 0x9d, 0xa1, 0xb9, 0xad, 0x1e, 0x72, 0xe8, 0x0c, 0xf4, 0x9d, 0xe2, 0xb3, 0xef, 0xac, 0xc2,
	0xd6, 0x1f, 0x06, 0x54, 0x0e, 0xa4, 0x23, 0xda, 0x07, 0xf2, 0x08, 0xaa, 0x71, 0xd6, 0x1d, 0xb4,
	0xbc, 0xbc, 0xfb, 0x76, 0x23, 0x1b, 0xa0, 0x46, 0xce, 0x63, 0x7b, 0xe9, 0x45, 0x62, 0x15, 0xc6,
	0x89, 0x35, 0xdf, 0xc3, 0x6f, 0x9a, 0xd7, 0x40, 0x3e, 0x00, 0xd0, 0x04, 0x19, 0x09, 0xe9, 0x53,
	0xc5, 0xbe, 0x3a, 0x4e, 0x2c, 0xb3, 0xcf, 0x46, 0xaf, 0x13, 0x0b, 0x1e, 0x4f, 0x98, 0x34, 0x03,
	0x24, 0x2d, 0xa8, 0xe8, 0xaf, 0x2f, 0x65, 0xbc, 0xeb, 0xe6, 0xa6, 0xb9, 0x5d, 0xde, 0x7d, 0xab,
	0x71, 0xd2, 0x50, 0xf1, 0x47, 0xb3, 0x9f, 0x38, 0xbe, 0xd7, 0x71, 0x04, 0x8f, 0xec, 0x2d, 0x6d,
	0x44, 0x09, 0xb9, 0xcf, 0x5f, 0x59, 0xb5, 0xac, 0x5f, 0xa8, 0x82, 0xe6, 0x14, 0xea, 0x08, 0xfc,
	0x62, 0xc2, 0x95, 0x07, 0x71, 0xf7, 0x9e, 0xef, 0x78, 0x83, 0xff, 0xc3, 0xfb, 0x2f, 0x00, 0x06,
	0x2c, 0xea, 0xfb, 0x8c, 0x72, 0x2e, 0xd0, 0x7b, 0xe5, 0x44, 0x46, 0xdf, 0xbe, 0x13, 0xf7, 0xa8,
	0x13, 0x74, 0x99, 0xbd, 0xaa, 0x75, 0x95, 0x95, 0x48, 0x2b, 0xe2, 0x5c, 0xd0, 0x8c, 0x3c, 0xd9,
	0x85, 0xb2, 0xe0, 0xc2, 0xf1, 0x0f, 0x22, 0xce, 0x8f, 0x62, 0x9d, 0xf2, 0x95, 0x71, 0x62, 0x55,
	0x90, 0xdc, 0x0a, 0x91, 0x4e, 0xb3, 0x20, 0xd2, 0x85, 0xf2, 0x51, 0xc4, 0x07, 0xcd, 0x4e, 0x27,
	0x62, 0x71, 0x5c, 0x2f, 0x62, 0x02, 0xf6, 0xa4, 0x8c, 0x24, 0xb7, 0x1c, 0x45, 0x7f, 0x9d, 0x58,
	0xef, 0x75, 0x3d, 0xd1, 0x1b, 0xb6, 0x1b, 0x2e, 0x1f, 0xec, 0x84, 0xbc, 0x2f, 0x6e, 0x06, 0x4c,
	0x3c, 0xe5, 0x51, 0x5f, 0x97, 0xca, 0x4d, 0x2c, 0x1b, 0x31, 0x0a, 0x59, 0xdc, 0xd0, 0xca, 0x68,
	0x56, 0x33, 0xd9, 0x83, 0x0a, 0x3b, 0xf6, 0x3a, 0x2c, 0x70, 0xd9, 0xe1, 0x28, 0x64, 0xf5, 0xd2,
	0xa6, 0xb1, 0x5d, 0xb2, 0xdf, 0x19, 0x27, 0x56, 0x35, 0xa5, 0xb7, 0xa4, 0xf8, 0xeb, 0xc4, 0xaa,
	0xec, 0x65, 0x80, 0x34, 0x27, 0x46, 0x9a, 0xb0, 0xc2, 0x4e, 0x42, 0x2f, 0xc2, 0x92, 0xd0, 0x77,
	0x7b, 0x1e, 0x1d, 0x95, 0xb7, 0xa6, 0x36, 0xe5, 0xa5, 0xd7, 0xfb, 0x02, 0xfc, 0xce, 0x15, 0x99,
	0xda, 0x67, 0xdf, 0x5b, 0xc6, 0xd6, 0x6f, 0x06, 0x54, 0x1f, 0xc4, 0x5d, 0xbc, 0x0b, 0x18, 0x0f,
	0x42, 0x41, 0x47, 0x17, 0x3f, 0x75, 0x86, 0xd7, 0xf3, 0x19, 0x79, 0x30, 0x05, 0xd8, 0x57, 0x75,
	0x4e, 0xaa, 0x3a, 0x27, 0x69, 0x88, 0x33, 0x4a, 0xc8, 0x6d, 0x28, 0xfa, 0xcc, 0x39, 0xd2, 0xe9,
	0x5d, 0xcb, 0x2b, 0x43, 0xc8, 0x7d, 0xbb, 0xa2, 0xf5, 0x20, 0x92, 0xe2, 0xef, 0x85, 0x88, 0x99,
	0xff, 0x28, 0x62, 0x19, 0x77, 0x7f, 0x30, 0x60, 0x5e, 0x9d, 0x47, 0xee, 0x00, 0x44, 0xcc, 0x77,
	0x46, 0x59, 0x37, 0xeb, 0x79, 0xcb, 0xe8, 0x84, 0xbf, 0x5f, 0xa0, 0x19, 0x34, 0x79, 0x04, 0x4b,
	0x6e, 0xcf, 0xf1, 0x7d, 0x16, 0x74, 0x75, 0x98, 0x94, 0x67, 0xd7, 0xf3, 0xf2, 0xf7, 0x72, 0x98,
	0xfb, 0xc1, 0xb1, 0xac, 0xc6, 0x4f, 0x1c, 0xe1, 0xec, 0x17, 0xe8, 0x39, 0x05, 0xaa, 0xda, 0xec,
	0x05, 0x28, 0x61, 0xfc, 0xb6, 0xce, 0xe6, 0xa0, 0x8a, 0x49, 0x49, 0xdd, 0x22, 0x3b, 0x00, 0x6d,
	0x9f, 0xf3, 0x81, 0x3d, 0x12, 0x2c, 0x46, 0x7b, 0x2b, 0xf6, 0xb2, 0xac, 0x05, 0xa4, 0xb6, 0xda,
	0x92, 0x4c, 0x33, 0x10, 0xf2, 0xe4, 0x7c, 0xb1, 0xce, 0xfd, 0x75, 0xb1, 0xae, 0x8e, 0x13, 0x6b,
	0x79, 0x12, 0xda, 0xd9, 0x15, 0x7b, 0x0b, 0xca, 0xc1, 0x70, 0xf0, 0xf0, 0x28, 0x57, 0x63, 0x35,
	0x99, 0x93, 0x60, 0x38, 0x68, 0xf1, 0xa3, 0xc9, 0x0d, 0xc8, 0xa0, 0xc8, 0xa7, 0x30, 0xaf, 0xc8,
	0xf5, 0x22, 0xf6, 0xa9, 0xd9, 0x77, 0x60, 0x3d, 0xed, 0x15, 0x0a, 0xfb, 0xfc, 0x95, 0xb5, 0xa0,
	0x38, 0x31, 0xd5, 0xa4, 0xff, 0xa8, 0x88, 0x74, 0x73, 0x7b, 0x66, 0x02, 0x4c, 0x93, 0x2c, 0xbb,
	0x47, 0xc4, 0xbe, 0x19, 0xb2, 0x58, 0xc8, 0x96, 0xa3, 0x87, 0x12, 0x76, 0x0f, 0x4d, 0x6e, 0xf5,
	0x64, 0x2b, 0xca, 0x82, 0xc8, 0xbb, 0xb0, 0xc0, 0x02, 0x11, 0xf1, 0x50, 0xb5, 0x6e, 0xd3, 0x2e,
	0x8f, 0x13, 0x2b, 0x25, 0xd1, 0xf4, 0x85, 0xec, 0x5f, 0x32, 0x92, 0xea, 0xe3, 0xc4, 0x5a, 0x4b,
	0x47, 0x52, 0x5b, 0xb2, 0x2f, 0x19, 0x4c, 0xe4, 0x2e, 0x2c, 0xc5, 0x2c, 0x3a, 0xf6, 0x5c, 0x16,
	0xe9, 0xe1, 0x59, 0x44, 0x3b, 0xd7, 0xc6, 0x89, 0xb5, 0x92, 0x72, 0xe4, 0x04, 0xc5, 0xf1, 0x79,
	0x0e, 0x4b, 0x1a, 0x78, 0x8b, 0xdc, 0xbe, 0x1a, 0xa0, 0x25, 0x94, 0x5c, 0x1a, 0x27, 0x56, 0x86,
	0x4a, 0x33, 0xef, 0xe4, 0x7d, 0x28, 0x09, 0xde, 0x67, 0x01, 0x76, 0x98, 0xf2, 0x6e, 0x2d, 0x9f,
	0xb6, 0x66, 0xf3, 0xd0, 0x2e, 0xeb, 0x9c, 0x99, 0x8e, 0x23, 0xa8, 0x02, 0x93, 0x1b, 0xb0, 0x18,
	0x7b, 0xdd, 0xc0, 0x11, 0xc3, 0x88, 0xd5, 0x17, 0xf0, 0x90, 0xea, 0x38, 0xb1, 0xa6, 0x44, 0x3a,
	0x7d, 0xd5, 0xa9, 0x38, 0x9d, 0x83, 0xf5, 0x37, 0xd6, 0x0b, 0x61, 0x50, 0x1b, 0x38, 0x5f, 0xf3,
	0xc8, 0x13, 0x23, 0xca, 0xe2, 0x90, 0x07, 0x31, 0xd6, 0x80, 0x79, 0xf1, 0x3e, 0x63, 0x3a, 0x53,
	0x8c, 0x7d, 0x4d, 0x1b, 0x47, 0x52, 0xe9, 0x56, 0x94, 0x8a, 0xd3, 0x8b, 0x1a, 0x49, 0x1b, 0x56,
	0x06, 0x5e, 0x90, 0x23, 0xce, 0xae, 0x9a, 0xfc, 0x29, 0xe9, 0xb5, 0xad, 0xa5, 0xc2, 0x93, 0x53,
	0xe8, 0x05, 0x7d, 0x44, 0xc0, 0x72, 0xc4, 0x42, 0x1e, 0x09, 0x16, 0xa5, 0x23, 0xc7, 0xc4, 0x62,
	0xfe, 0x4c, 0x6a, 0x48, 0x59, 0xf1, 0xbf, 0x9b, 0x3b, 0xe7, 0x8f, 0xd0, 0x41, 0x7e, 0x6e, 0x40,
	0x35, 0x67, 0x7a, 0x3e, 0x53, 0xc6, 0xe5, 0x99, 0x22, 0xd7, 0xe1, 0x4a, 0x94, 0x0d, 0xcb, 0xa2,
	0xba, 0xec, 0xa1, 0x33, 0xf2, 0xb9, 0xd3, 0xa1, 0x13, 0x26, 0xf9, 0x48, 0xb7, 0x31, 0xf4, 0xec,
	0x92, 0xb6, 0x6a, 0x57, 0xd3, 0xad, 0x04, 0xe1, 0x54, 0x3d, 0xb4, 0xb1, 0xbf, 0x1b, 0x60, 0x36,
	0x9b, 0x87, 0xb2, 0xc2, 0x8e, 0x59, 0x24, 0xcb, 0x40, 0x1b, 0x88, 0x87, 0x6a, 0x12, 0x4d, 0x5f,
	0xc8, 0x3d, 0x58, 0xcb, 0xaf, 0x8a, 0xbe, 0xe7, 0xa6, 0x0b, 0xd5, 0xa2, 0xea, 0x94, 0x7a, 0xb5,
	0xc4, 0xc2, 0x98, 0x09, 0x26, 0x77, 0x61, 0xd9, 0xf5, 0x3d, 0x16, 0x88, 0xa9, 0xbc, 0x39, 0x5d,
	0x4d, 0x15, 0x6b, 0xa2, 0xe2, 0x3c, 0x94, 0x34, 0x73, 0x26, 0x3c, 0x9e, 0xc4, 0xb5, 0x38, 0x2b,
	0xae, 0x33, 0xa1, 0xda, 0xf5, 0x9f, 0x0c, 0x28, 0x67, 0x66, 0x2c, 0xb9, 0x01, 0xe5, 0x43, 0x27,
	0xea, 0x32, 0x71, 0x3f, 0xe8, 0xb0, 0x13, 0x0c, 0x83, 0xa9, 0xf6, 0x5e, 0x4f, 0x12, 0x68, 0x96,
	0x2b, 0x37, 0xaa, 0x5e, 0xba, 0x31, 0xc5, 0xf5, 0xb9, 0xc9, 0x5a, 0x78, 0xf9, 0x46, 0x25, 0x45,
	0x5a, 0x11, 0xca, 0xd0, 0x8c, 0x3c, 0xd9, 0x83, 0x79, 0x81, 0xca, 0x75, 0x2e, 0xdf, 0xa8, 0x69,
	0x4d, 0x6b, 0xaa, 0x28, 0xb8, 0xd2, 0x45, 0xb5, 0xb0, 0xf6, 0xeb, 0x21, 0x94, 0x10, 0x2c, 0x57,
	0x78, 0x9f, 0x3f, 0xd5, 0x0b, 0x64, 0x51, 0xb9, 0x82, 0x04, 0xaa, 0x1e, 0x12, 0x30, 0x0c, 0x43,
	0x3d, 0xb4, 0x34, 0x00, 0x09, 0x54, 0x3d, 0xb4, 0x42, 0x0f, 0x16, 0x27, 0x16, 0x90, 0x2d, 0x28,
	0xf6, 0xd2, 0xbe, 0x5d, 0x51, 0x5d, 0x4d, 0x2d, 0x21, 0x08, 0x41, 0x1e, 0xf9, 0x10, 0x4a, 0x68,
	0x98, 0x2e, 0xeb, 0xd5, 0x73, 0x37, 0x13, 0x3d, 0x99, 0x5c, 0x4a, 0xe5, 0x82, 0x7a, 0xd8, 0x07,
	0x2f, 0x4e, 0x37, 0x8c, 0x97, 0xa7, 0x1b, 0xc6, 0xaf, 0xa7, 0x1b, 0xc6, 0xb7, 0x67, 0x1b, 0x85,
	0x97, 0x67, 0x1b, 0x85, 0x9f, 0xcf, 0x36, 0x0a, 0x5f, 0xdd, 0xfe, 0x3b, 0xf5, 0x99, 0xfb, 0x6f,
	0x85, 0xc5, 0xda, 0x9e, 0xc7, 0xbf, 0x48, 0xb7, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xba, 0xeb,
	0x4c, 0x24, 0x78, 0x0d, 0x00, 0x00,
}

func (m *SessionHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SessionHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SessionHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SessionBlockHeight != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.SessionBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ApplicationPubKey) > 0 {
		i -= len(m.ApplicationPubKey)
		copy(dAtA[i:], m.ApplicationPubKey)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.ApplicationPubKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProtoSession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProtoSession) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProtoSession) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SessionNodes) > 0 {
		for iNdEx := len(m.SessionNodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SessionNodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.SessionKey) > 0 {
		i -= len(m.SessionKey)
		copy(dAtA[i:], m.SessionKey)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.SessionKey)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.SessionHeader.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpirationHeight != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.ExpirationHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.EvidenceType != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.EvidenceType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.TotalProofs != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.TotalProofs))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.MerkleRoot.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.SessionHeader.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgProtoProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProtoProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProtoProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EvidenceType != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.EvidenceType))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Leaf.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.MerkleProof.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ProofI) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProofI) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofI) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proof != nil {
		{
			size := m.Proof.Size()
			i -= size
			if _, err := m.Proof.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *ProofI_RelayProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofI_RelayProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.RelayProof != nil {
		{
			size, err := m.RelayProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPocket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *ProofI_ChallengeProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProofI_ChallengeProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ChallengeProof != nil {
		{
			size, err := m.ChallengeProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPocket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ProtoEvidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProtoEvidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProtoEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EvidenceType != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.EvidenceType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Proofs) > 0 {
		for iNdEx := len(m.Proofs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Proofs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.NumOfProofs != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.NumOfProofs))
		i--
		dAtA[i] = 0x18
	}
	if m.SessionHeader != nil {
		{
			size, err := m.SessionHeader.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPocket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.BloomBytes) > 0 {
		i -= len(m.BloomBytes)
		copy(dAtA[i:], m.BloomBytes)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.BloomBytes)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RelayProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size, err := m.Token.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Blockchain) > 0 {
		i -= len(m.Blockchain)
		copy(dAtA[i:], m.Blockchain)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.Blockchain)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ServicerPubKey) > 0 {
		i -= len(m.ServicerPubKey)
		copy(dAtA[i:], m.ServicerPubKey)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.ServicerPubKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.SessionBlockHeight != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.SessionBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.Entropy != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.Entropy))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RequestHash) > 0 {
		i -= len(m.RequestHash)
		copy(dAtA[i:], m.RequestHash)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.RequestHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChallengeProofInvalidData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChallengeProofInvalidData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChallengeProofInvalidData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReporterAddress) > 0 {
		i -= len(m.ReporterAddress)
		copy(dAtA[i:], m.ReporterAddress)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.ReporterAddress)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.MinorityResponse.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.MajorityResponses) > 0 {
		for iNdEx := len(m.MajorityResponses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MajorityResponses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RelayResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Response) > 0 {
		i -= len(m.Response)
		copy(dAtA[i:], m.Response)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.Response)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AAT) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AAT) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AAT) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ApplicationSignature) > 0 {
		i -= len(m.ApplicationSignature)
		copy(dAtA[i:], m.ApplicationSignature)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.ApplicationSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ClientPublicKey) > 0 {
		i -= len(m.ClientPublicKey)
		copy(dAtA[i:], m.ClientPublicKey)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.ClientPublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ApplicationPublicKey) > 0 {
		i -= len(m.ApplicationPublicKey)
		copy(dAtA[i:], m.ApplicationPublicKey)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.ApplicationPublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MerkleProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MerkleProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MerkleProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Target.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.HashRanges) > 0 {
		for iNdEx := len(m.HashRanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HashRanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPocket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TargetIndex != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.TargetIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Range) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Range) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Range) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Upper != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.Upper))
		i--
		dAtA[i] = 0x10
	}
	if m.Lower != 0 {
		i = encodeVarintPocket(dAtA, i, uint64(m.Lower))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HashRange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashRange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashRange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Range.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPocket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintPocket(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPocket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPocket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SessionHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ApplicationPubKey)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	if m.SessionBlockHeight != 0 {
		n += 1 + sovPocket(uint64(m.SessionBlockHeight))
	}
	return n
}

func (m *ProtoSession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SessionHeader.Size()
	n += 1 + l + sovPocket(uint64(l))
	l = len(m.SessionKey)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	if len(m.SessionNodes) > 0 {
		for _, e := range m.SessionNodes {
			l = e.Size()
			n += 1 + l + sovPocket(uint64(l))
		}
	}
	return n
}

func (m *MsgClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SessionHeader.Size()
	n += 1 + l + sovPocket(uint64(l))
	l = m.MerkleRoot.Size()
	n += 1 + l + sovPocket(uint64(l))
	if m.TotalProofs != 0 {
		n += 1 + sovPocket(uint64(m.TotalProofs))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	if m.EvidenceType != 0 {
		n += 1 + sovPocket(uint64(m.EvidenceType))
	}
	if m.ExpirationHeight != 0 {
		n += 1 + sovPocket(uint64(m.ExpirationHeight))
	}
	return n
}

func (m *MsgProtoProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MerkleProof.Size()
	n += 1 + l + sovPocket(uint64(l))
	l = m.Leaf.Size()
	n += 1 + l + sovPocket(uint64(l))
	if m.EvidenceType != 0 {
		n += 1 + sovPocket(uint64(m.EvidenceType))
	}
	return n
}

func (m *ProofI) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Proof != nil {
		n += m.Proof.Size()
	}
	return n
}

func (m *ProofI_RelayProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RelayProof != nil {
		l = m.RelayProof.Size()
		n += 1 + l + sovPocket(uint64(l))
	}
	return n
}
func (m *ProofI_ChallengeProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChallengeProof != nil {
		l = m.ChallengeProof.Size()
		n += 1 + l + sovPocket(uint64(l))
	}
	return n
}
func (m *ProtoEvidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BloomBytes)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	if m.SessionHeader != nil {
		l = m.SessionHeader.Size()
		n += 1 + l + sovPocket(uint64(l))
	}
	if m.NumOfProofs != 0 {
		n += 1 + sovPocket(uint64(m.NumOfProofs))
	}
	if len(m.Proofs) > 0 {
		for _, e := range m.Proofs {
			l = e.Size()
			n += 1 + l + sovPocket(uint64(l))
		}
	}
	if m.EvidenceType != 0 {
		n += 1 + sovPocket(uint64(m.EvidenceType))
	}
	return n
}

func (m *RelayProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequestHash)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	if m.Entropy != 0 {
		n += 1 + sovPocket(uint64(m.Entropy))
	}
	if m.SessionBlockHeight != 0 {
		n += 1 + sovPocket(uint64(m.SessionBlockHeight))
	}
	l = len(m.ServicerPubKey)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = len(m.Blockchain)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = m.Token.Size()
	n += 1 + l + sovPocket(uint64(l))
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	return n
}

func (m *ChallengeProofInvalidData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MajorityResponses) > 0 {
		for _, e := range m.MajorityResponses {
			l = e.Size()
			n += 1 + l + sovPocket(uint64(l))
		}
	}
	l = m.MinorityResponse.Size()
	n += 1 + l + sovPocket(uint64(l))
	l = len(m.ReporterAddress)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	return n
}

func (m *RelayResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = len(m.Response)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = m.Proof.Size()
	n += 1 + l + sovPocket(uint64(l))
	return n
}

func (m *AAT) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = len(m.ApplicationPublicKey)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = len(m.ClientPublicKey)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = len(m.ApplicationSignature)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	return n
}

func (m *MerkleProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TargetIndex != 0 {
		n += 1 + sovPocket(uint64(m.TargetIndex))
	}
	if len(m.HashRanges) > 0 {
		for _, e := range m.HashRanges {
			l = e.Size()
			n += 1 + l + sovPocket(uint64(l))
		}
	}
	l = m.Target.Size()
	n += 1 + l + sovPocket(uint64(l))
	return n
}

func (m *Range) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Lower != 0 {
		n += 1 + sovPocket(uint64(m.Lower))
	}
	if m.Upper != 0 {
		n += 1 + sovPocket(uint64(m.Upper))
	}
	return n
}

func (m *HashRange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovPocket(uint64(l))
	}
	l = m.Range.Size()
	n += 1 + l + sovPocket(uint64(l))
	return n
}

func sovPocket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPocket(x uint64) (n int) {
	return sovPocket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SessionHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SessionHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SessionHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionBlockHeight", wireType)
			}
			m.SessionBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProtoSession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProtoSession: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProtoSession: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SessionHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionKey = append(m.SessionKey[:0], dAtA[iNdEx:postIndex]...)
			if m.SessionKey == nil {
				m.SessionKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionNodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionNodes = append(m.SessionNodes, types.ProtoValidator{})
			if err := m.SessionNodes[len(m.SessionNodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SessionHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MerkleRoot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalProofs", wireType)
			}
			m.TotalProofs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalProofs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = append(m.FromAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.FromAddress == nil {
				m.FromAddress = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceType", wireType)
			}
			m.EvidenceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvidenceType |= EvidenceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpirationHeight", wireType)
			}
			m.ExpirationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpirationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProtoProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProtoProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProtoProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MerkleProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaf", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Leaf.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceType", wireType)
			}
			m.EvidenceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvidenceType |= EvidenceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProofI) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProofI: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProofI: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RelayProof{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Proof = &ProofI_RelayProof{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ChallengeProofInvalidData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Proof = &ProofI_ChallengeProof{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProtoEvidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProtoEvidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProtoEvidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BloomBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BloomBytes = append(m.BloomBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.BloomBytes == nil {
				m.BloomBytes = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SessionHeader == nil {
				m.SessionHeader = &SessionHeader{}
			}
			if err := m.SessionHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumOfProofs", wireType)
			}
			m.NumOfProofs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumOfProofs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proofs = append(m.Proofs, ProofI{})
			if err := m.Proofs[len(m.Proofs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceType", wireType)
			}
			m.EvidenceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvidenceType |= EvidenceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RelayProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entropy", wireType)
			}
			m.Entropy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Entropy |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionBlockHeight", wireType)
			}
			m.SessionBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServicerPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServicerPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blockchain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blockchain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Token.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChallengeProofInvalidData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChallengeProofInvalidData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChallengeProofInvalidData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MajorityResponses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MajorityResponses = append(m.MajorityResponses, RelayResponse{})
			if err := m.MajorityResponses[len(m.MajorityResponses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinorityResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinorityResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReporterAddress = append(m.ReporterAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.ReporterAddress == nil {
				m.ReporterAddress = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RelayResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Response = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AAT) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AAT: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AAT: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationSignature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationSignature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MerkleProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MerkleProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MerkleProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetIndex", wireType)
			}
			m.TargetIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashRanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashRanges = append(m.HashRanges, HashRange{})
			if err := m.HashRanges[len(m.HashRanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Target.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Range) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Range: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Range: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lower", wireType)
			}
			m.Lower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lower |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upper", wireType)
			}
			m.Upper = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Upper |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashRange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashRange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashRange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Range", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPocket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPocket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Range.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPocket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPocket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPocket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPocket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPocket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPocket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPocket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPocket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPocket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPocket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPocket = fmt.Errorf("proto: unexpected end of group")
)
