// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/apps/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/duration"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the staking module.
type Params struct {
	UnstakingTime       time.Duration `protobuf:"bytes,1,opt,name=unstaking_time,json=unstakingTime,proto3,stdduration" json:"unstaking_time" yaml:"unstaking_time"`
	MaxApplications     int64         `protobuf:"varint,2,opt,name=max_applications,json=maxApplications,proto3" json:"max_applications" yaml:"max_applications"`
	AppStakeMin         int64         `protobuf:"varint,3,opt,name=app_stake_min,json=appStakeMin,proto3" json:"app_stake_minimum" yaml:"app_stake_minimum"`
	BaseRelaysPerPOKT   int64         `protobuf:"varint,4,opt,name=base_relays_perPOKT,json=baseRelaysPerPOKT,proto3" json:"base_relays_per_pokt" yaml:"base_relays_per_pokt"`
	StabilityAdjustment int64         `protobuf:"varint,5,opt,name=stability_adjustment,json=stabilityAdjustment,proto3" json:"stability_adjustment" yaml:"stability_adjustment"`
	ParticipationRateOn bool          `protobuf:"varint,6,opt,name=participation_rate_on,json=participationRateOn,proto3" json:"participation_rate_on" yaml:"participation_rate_on"`
	MaxChains           int64         `protobuf:"varint,7,opt,name=max_chains,json=maxChains,proto3" json:"maximum_chains" yaml:"maximum_chains"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c08bf9007e04c063, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetUnstakingTime() time.Duration {
	if m != nil {
		return m.UnstakingTime
	}
	return 0
}

func (m *Params) GetMaxApplications() int64 {
	if m != nil {
		return m.MaxApplications
	}
	return 0
}

func (m *Params) GetAppStakeMin() int64 {
	if m != nil {
		return m.AppStakeMin
	}
	return 0
}

func (m *Params) GetBaseRelaysPerPOKT() int64 {
	if m != nil {
		return m.BaseRelaysPerPOKT
	}
	return 0
}

func (m *Params) GetStabilityAdjustment() int64 {
	if m != nil {
		return m.StabilityAdjustment
	}
	return 0
}

func (m *Params) GetParticipationRateOn() bool {
	if m != nil {
		return m.ParticipationRateOn
	}
	return false
}

func (m *Params) GetMaxChains() int64 {
	if m != nil {
		return m.MaxChains
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "x.apps.Params")
}

func init() { proto.RegisterFile("x/apps/params.proto", fileDescriptor_c08bf9007e04c063) }

var fileDescriptor_c08bf9007e04c063 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xb1, 0x6e, 0xd3, 0x40,
	0x18, 0x80, 0x63, 0x4a, 0x43, 0x71, 0x55, 0x20, 0x4e, 0x2a, 0x4c, 0x41, 0xbe, 0xc8, 0x53, 0x24,
	0x54, 0x1b, 0xe8, 0x80, 0xe8, 0xd6, 0xc0, 0x54, 0x84, 0x1a, 0x99, 0xb2, 0x74, 0xb1, 0xfe, 0xb8,
	0x87, 0x7b, 0x4d, 0xce, 0x77, 0xb2, 0xcf, 0xc2, 0x79, 0x0b, 0xc6, 0x8e, 0x7d, 0x9c, 0x0e, 0x0c,
	0x1d, 0x99, 0x0e, 0x94, 0x2c, 0x28, 0x63, 0x9e, 0x00, 0xdd, 0x39, 0x24, 0x24, 0xf5, 0x12, 0x5d,
	0xbe, 0xcf, 0xfe, 0x7e, 0xf9, 0x7c, 0x36, 0x9b, 0x85, 0x0f, 0x9c, 0x67, 0x3e, 0x87, 0x14, 0x68,
	0xe6, 0xf1, 0x94, 0x09, 0x66, 0xd5, 0x0b, 0x4f, 0xc1, 0xbd, 0x56, 0xcc, 0x62, 0xa6, 0x91, 0xaf,
	0x56, 0xa5, 0xdd, 0x73, 0x62, 0xc6, 0xe2, 0x21, 0xf6, 0xf5, 0xbf, 0x7e, 0xfe, 0xd5, 0x3f, 0xcf,
	0x53, 0x10, 0x84, 0x25, 0x73, 0xdf, 0x98, 0x27, 0xd5, 0x4f, 0x89, 0xdc, 0x1f, 0x9b, 0x66, 0xbd,
	0xa7, 0x27, 0x58, 0xb9, 0xf9, 0x28, 0x4f, 0x32, 0x01, 0x03, 0x92, 0xc4, 0xa1, 0x20, 0x14, 0xdb,
	0x46, 0xdb, 0xe8, 0x6c, 0xbf, 0x79, 0xe6, 0x95, 0x59, 0xef, 0x5f, 0xd6, 0xfb, 0x30, 0xcf, 0x76,
	0x0f, 0x6e, 0x24, 0xaa, 0x4d, 0x25, 0x5a, 0xbb, 0x71, 0x26, 0xd1, 0xee, 0x08, 0xe8, 0xf0, 0xd0,
	0x5d, 0xe5, 0xee, 0xd5, 0x2f, 0x64, 0x04, 0x3b, 0x0b, 0x78, 0x4a, 0x28, 0xb6, 0xce, 0xcc, 0x27,
	0x14, 0x8a, 0x10, 0x38, 0x1f, 0x92, 0x48, 0x67, 0x33, 0xfb, 0x5e, 0xdb, 0xe8, 0x6c, 0x74, 0xfd,
	0xa9, 0x44, 0x77, 0xdc, 0x4c, 0xa2, 0xa7, 0x65, 0x7b, 0xdd, 0xb8, 0xc1, 0x63, 0x0a, 0xc5, 0xd1,
	0x7f, 0xc4, 0xfa, 0x62, 0xee, 0x00, 0xe7, 0xa1, 0x1a, 0x87, 0x43, 0x4a, 0x12, 0x7b, 0x43, 0x87,
	0x5f, 0x4f, 0x25, 0x6a, 0xac, 0x08, 0x42, 0x73, 0x3a, 0x93, 0xc8, 0x2e, 0xcb, 0x77, 0x94, 0x1b,
	0x6c, 0x03, 0xe7, 0x9f, 0x15, 0xfa, 0x44, 0x12, 0x2b, 0x36, 0x9b, 0x7d, 0xc8, 0x70, 0x98, 0xe2,
	0x21, 0x8c, 0xb2, 0x90, 0xe3, 0xb4, 0x77, 0xf2, 0xf1, 0xd4, 0xbe, 0xaf, 0xe3, 0x6f, 0xa7, 0x12,
	0xb5, 0xd6, 0x74, 0xc8, 0xd9, 0x40, 0xcc, 0x24, 0x7a, 0x5e, 0xf6, 0xab, 0xac, 0x1b, 0x34, 0x14,
	0x0e, 0x34, 0xed, 0x95, 0x45, 0xeb, 0xd2, 0x6c, 0x65, 0x02, 0xfa, 0x64, 0x48, 0xc4, 0x28, 0x84,
	0xf3, 0xcb, 0x3c, 0x13, 0x14, 0x27, 0xc2, 0xde, 0x5c, 0x4e, 0xaa, 0xf2, 0xcb, 0x49, 0x55, 0xd6,
	0x0d, 0x9a, 0x0b, 0x7c, 0xb4, 0xa0, 0x16, 0x35, 0x77, 0x39, 0xa4, 0x82, 0x44, 0x84, 0xeb, 0xdd,
	0x0b, 0x53, 0x10, 0x38, 0x64, 0x89, 0x5d, 0x6f, 0x1b, 0x9d, 0xad, 0xee, 0xbb, 0xa9, 0x44, 0xd5,
	0x17, 0xcc, 0x24, 0x7a, 0x51, 0x4e, 0xab, 0xd4, 0x6e, 0xd0, 0x5c, 0xe1, 0x01, 0x08, 0x7c, 0x92,
	0x58, 0xc7, 0xa6, 0xa9, 0x5e, 0x60, 0x74, 0x01, 0x24, 0xc9, 0xec, 0x07, 0xfa, 0x81, 0x5e, 0xaa,
	0xa3, 0x44, 0xa1, 0x50, 0x5b, 0x3e, 0x37, 0xcb, 0xa3, 0xb4, 0xca, 0xdd, 0xe0, 0x21, 0x85, 0xe2,
	0xbd, 0x5e, 0x1f, 0x6e, 0x5d, 0x5d, 0xa3, 0xda, 0x9f, 0x6b, 0x64, 0x74, 0x8f, 0x6f, 0xc6, 0x8e,
	0x71, 0x3b, 0x76, 0x8c, 0xdf, 0x63, 0xc7, 0xf8, 0x3e, 0x71, 0x6a, 0xb7, 0x13, 0xa7, 0xf6, 0x73,
	0xe2, 0xd4, 0xce, 0x5e, 0xc5, 0x44, 0x5c, 0xe4, 0x7d, 0x2f, 0x62, 0xd4, 0x57, 0xfb, 0xbd, 0x9f,
	0x60, 0xf1, 0x8d, 0xa5, 0x03, 0x9f, 0xb3, 0x68, 0x80, 0xc5, 0x7e, 0xc4, 0x52, 0xec, 0xcf, 0xbf,
	0x0f, 0x31, 0xe2, 0x38, 0xeb, 0xd7, 0xf5, 0x79, 0x3f, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x15,
	0x9f, 0x3f, 0x80, 0x89, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UnstakingTime != that1.UnstakingTime {
		return false
	}
	if this.MaxApplications != that1.MaxApplications {
		return false
	}
	if this.AppStakeMin != that1.AppStakeMin {
		return false
	}
	if this.BaseRelaysPerPOKT != that1.BaseRelaysPerPOKT {
		return false
	}
	if this.StabilityAdjustment != that1.StabilityAdjustment {
		return false
	}
	if this.ParticipationRateOn != that1.ParticipationRateOn {
		return false
	}
	if this.MaxChains != that1.MaxChains {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxChains != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxChains))
		i--
		dAtA[i] = 0x38
	}
	if m.ParticipationRateOn {
		i--
		if m.ParticipationRateOn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.StabilityAdjustment != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.StabilityAdjustment))
		i--
		dAtA[i] = 0x28
	}
	if m.BaseRelaysPerPOKT != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BaseRelaysPerPOKT))
		i--
		dAtA[i] = 0x20
	}
	if m.AppStakeMin != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AppStakeMin))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxApplications != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxApplications))
		i--
		dAtA[i] = 0x10
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.UnstakingTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.UnstakingTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.UnstakingTime)
	n += 1 + l + sovParams(uint64(l))
	if m.MaxApplications != 0 {
		n += 1 + sovParams(uint64(m.MaxApplications))
	}
	if m.AppStakeMin != 0 {
		n += 1 + sovParams(uint64(m.AppStakeMin))
	}
	if m.BaseRelaysPerPOKT != 0 {
		n += 1 + sovParams(uint64(m.BaseRelaysPerPOKT))
	}
	if m.StabilityAdjustment != 0 {
		n += 1 + sovParams(uint64(m.StabilityAdjustment))
	}
	if m.ParticipationRateOn {
		n += 2
	}
	if m.MaxChains != 0 {
		n += 1 + sovParams(uint64(m.MaxChains))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnstakingTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.UnstakingTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxApplications", wireType)
			}
			m.MaxApplications = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxApplications |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppStakeMin", wireType)
			}
			m.AppStakeMin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppStakeMin |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRelaysPerPOKT", wireType)
			}
			m.BaseRelaysPerPOKT = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseRelaysPerPOKT |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StabilityAdjustment", wireType)
			}
			m.StabilityAdjustment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StabilityAdjustment |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipationRateOn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ParticipationRateOn = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxChains", wireType)
			}
			m.MaxChains = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxChains |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
